#:schema node_modules/wrangler/config-schema.json
name = "tesla"
main = ".open-next/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[[routes]]
pattern = "tesla.orz.tw/*"
zone_name = "orz.tw"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"
